### PR TITLE
kn/add certificate

### PR DESCRIPTION
**Pull request by nielsenko**
- Add ISRG X1 Root certificate to SecurityContext of default HttpClient
- Update CHANGELOG

Fix: #1087 
Fix: #1370

### CODE REVIEW

**Review by blagoev — APPROVED** [review]

**Review by desistefanova — APPROVED** [review]

**Comment by dani-weiss** [comment]
I'd like to propose a change to the current code, @nielsenko .

Originally I had this issue and filed #1370. However, when I implemented my solution (similar to what you have in this PR), I noticed that on some windows machines, this would give me a tls exception. So I changed it to ignore the tls error caused by the certificate already being present on the machine.

This is my code:

```dart
 HttpClient? httpClient;
    try{
        final x1Cert = await rootBundle.loadString("assets/cert/isrg-root-x1.pem");
        final x2Cert = await rootBundle.loadString("assets/cert/isrg-root-x2.pem");

        final securityContext = SecurityContext.defaultContext;
        securityContext.setTrustedCertificatesBytes(utf8.encode(x1Cert));
        securityContext.setTrustedCertificatesBytes(utf8.encode(x2Cert));
        httpClient = HttpClient(context: securityContext);
    }
    on TlsException catch(e) {
      if(e.osError?.message.contains("CERT_ALREADY_IN_HASH_TABLE") == true) {
        // certificate is already trusted. Nothing to do here
      }
      else {
        rethrow;
      }
    }
```

**Comment by nielsenko** [comment]
@dani-weiss Thank you for your suggestion.

However, it will fall to someone else to update the PR to cater to this situation. I'm no longer working for MongoDB.

**Review by fealebenpae — APPROVED** [review]

**Comment by dani-weiss** [comment]
Did you see my [comment](#issuecomment-1786261633) above @nirinchev?

**Comment by nirinchev** [comment]
Yes - I'll fix that in a follow-up PR (I had fixed it locally, but didn't realize my push didn't go through).

**Pull request merged**
