### PR TITLE
fix release commit message

### PR DESCRIPTION
**Pull request by blagoev**

### CODE REVIEW

**Review by desistefanova — COMMENTED** [review]
Why is that change? It sounds to me OK the commit message to be 'Prepare for'.

**Review by nielsenko — COMMENTED** [review]
This will make us deviate somewhat from what realm-core, realm-dotnet, realm-java and realm-js does, but it is in line with realm-kotlin and realm-swift. Not usre if this is anything we want to align on, and in what direction we then would want to go.

**Comment by nirinchev** [comment]
I think the commit message is completely irrelevant and we should definitely not be spending time on aligning across SDKs. I don't care what it is - if you prefer square braces over no braces, go ahead and change it.

**Comment by nielsenko** [comment]
I'm fine with either too

**Pull request merged**
