### PR TITLE
Support maps

### PR DESCRIPTION
**Pull request by nielsenko**
Fixes https://github.com/realm/realm-dart/issues/685.
Fixes https://github.com/realm/realm-dart/issues/778.

TODO:

- [x] Add generator test for collection of collection
- [x] Add generator test for default values of collections
- [x] Add generator test for Set<Embedded>
- [x] Add changelog entry to clarify default values for lists are unsupported

### CODE REVIEW

**Comment by nielsenko** [comment]
Very early draft

**Comment by nielsenko** [comment]
@tanguy-penfen I assume so, but it is unlikely to be me doing it. The dedicated Dart team I was part of has been dissolved, and instead maintenance of the SDK has moved under the .NET team. Tagging @nirinchev as he may know more?

This is just a very early placeholder PR I created. 95% of the work is still outstanding.

**Comment by nielsenko** [comment]
This is related to https://github.com/realm/realm-dart/issues/685. I see @nirinchev has already commented there. Maps are not currently scheduled.

**Review by nielsenko — COMMENTED** [review]
I cannot approve this PR, since I initiated it, but this looks good to me, so you got my blessings to merge.. once the tests pass :-)

**Comment by jimisola** [comment]
Great news. From what version will this feature be available?

**Comment by nielsenko** [comment]
> Great news. From what version will this feature be available?

Next version

**Comment by nirinchev** [comment]
We want to include a few more bugfixes but hope to release it in the next few weeks.

**Pull request merged**
