### PR TITLE
Issue 877: Allow the realm DynamicLibrary to be opened from a path defined from …

### PR DESCRIPTION
**Pull request by nsivraj**
…an environment variable or dart define

https://github.com/realm/realm-dart/issues/877

### CODE REVIEW

**Comment by nsivraj** [comment]
@cla-bot check

**Comment by nsivraj** [comment]
This code is working for me in my command line dart compiled exe on my M1 mac. I have a few more tests to run to make sure it works correctly on linux and windows.

**Comment by nsivraj** [comment]
> This code is working for me in my command line dart compiled exe on my M1 mac. I have a few more tests to run to make sure it works correctly on linux and windows.

I have now verified that this works on windows, linux, and macos.

**Comment by nielsenko** [comment]
Hi Norman

Thanks for bringing this to our attention. I have merged your PR to a CI integration branch in order to run the full test suite (#882), and it passes fine. However, I have some quarrels merging this to master. 

I'm not too fond of the `dylib` package used, I would rather play nice with `DYLD_LIBRARY_PATH`, `LD_LIBRARY_PATH`, etc. instead of introducing this `LIBREALM_DART_PATH` environment variable (/ dart define).

I have created another PR: #881 that I would encourage you to look at. It basically changes the dlopen strategy to:

1. First try calling dlopen directly, allowing user to influence searched paths using `DYLD_LIBRARY_PATH`, `LD_LIBRARY_PATH`, etc depending on platform
2. Try to load it form the same directory as the executable, ie. if you compile to an exe you can place the realm lib next to it, and it will work.
3. Try to find a root project from either the placement of the script (Platform.script) and resolve `binary/<platform>/<realm_lib>` from there (ie. load `binary/macos/librealm_dart.so` on macos, etc.)
4. Do what we used to.

I wonder if that would not solve the issue you reported for you as well? Or is the custom environment variable and the dart define important for you?

**Pull request merged**
