### PR TITLE
Update to analyzer 5+

### PR DESCRIPTION
**Pull request by nielsenko**
Fixes: #1070, fixes: #1073

### CODE REVIEW

**Comment by desistefanova** [comment]
In this case we will have to remove the changelog item :
"Bump minimum Dart SDK version to 2.17.5 due to an issue with the Dart virtual machine when implementing `Finalizable`. ([dart-lang/sdk#49075](https://github.com/dart-lang/sdk/issues/49075))"
And also I have to update the docs: https://github.com/mongodb/docs-realm/pull/2416

**Review by blagoev — CHANGES_REQUESTED** [review]
Not sure we should do this yet. Lets discuss when is the appropriate time to do it.

**Comment by nielsenko** [comment]
If we want to work with latest stable, ie. 3.3.10 we need to do this.

**Comment by nielsenko** [comment]
> If we want to work with analyzer ^5.0.0 (which was released 3 month ago) we need latest stable, ie. 3.3.10, to do this. Community seems to want this.

My mistake, I'll drop this requirement

**Review by desistefanova — APPROVED** [review]

**Review by blagoev — APPROVED** [review]

**Pull request merged**
