### PR TITLE
kn/update analyzer

### PR DESCRIPTION
**Pull request by nielsenko**
- Update flutter and analyzer constraints to support analyzer ^6.0.0

Fix: #1357

### CODE REVIEW

**Comment by desistefanova** [comment]
I see, that the sdk version is increased here in order to force using the new analyzer, but I think we should wait until there is a solution on the [Linux issue](https://github.com/dart-lang/sdk/issues/53267) with the new flutter.

**Comment by nielsenko** [comment]
> I see, that the sdk version is increased here in order to force using the new analyzer, but I think we should wait until there is a solution on the [Linux issue](https://github.com/dart-lang/sdk/issues/53267) with the new flutter.

I tend to disagree. Very few people a using realm on linux, even fewer is using it outside flutter.

**Comment by nielsenko** [comment]
@nirinchev The linux issue holding this back has been fixed.

**Comment by nielsenko** [comment]
@nirinchev Sorry, you need to revert 6abe028d which is a temporary fix I did. Note that this PR will force users of the next version to use Flutter 3.13.0 or later (which is latest stable) to get Dart 3.1.0+

**Comment by sagnik-sanyal** [comment]
Hi there, when can we expect this PR to be merged ? We are waiting for this issue to be resolved

**Comment by nirinchev** [comment]
@sagnik-sanyal I've taken over this PR and expect to merge it soon. The reason why it's delayed is because I want to check how many users will be impacted by the flutter upgrade.

**Comment by nirinchev** [comment]
Based on our metrics, around 13% of our users are running on dart 3.1.0+. I'm a little hesitant to force the upgrade at this point unless you folks feel very confident that the flutter community is comfortable with always running latest and greatest.

**Comment by nielsenko** [comment]
👍

**Pull request merged**
